### ISSUE TITLE
upgrade file removal failing

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#380]
When doing an upgrade from 2.1-alpha2 to -alpha3, s9y wanted to remove files which lead to this error on my system:

```
2016-01-04 15:56:34: (mod_fastcgi.c.2673) FastCGI-stderr: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/var/www/supervise): failed to open dir: Permission denied' in /var/www/include/functions_upgrader.inc.php:340
2016-01-04 15:56:34: (mod_fastcgi.c.2673) FastCGI-stderr: Stack trace:
2016-01-04 15:56:34: (mod_fastcgi.c.2673) FastCGI-stderr: #0 [internal function]: RecursiveDirectoryIterator->__construct('/var/www/superv...', 0)
2016-01-04 15:56:34: (mod_fastcgi.c.2673) FastCGI-stderr: #1 /var/www/include/functions_upgrader.inc.php(340): RecursiveDirectoryIterator->getChildren()
2016-01-04 15:56:34: (mod_fastcgi.c.2673) FastCGI-stderr: #2 [internal function]: serendipity_removeDeadFiles_SPL('/var/www', Array, Array, true)
2016-01-04 15:56:34: (mod_fastcgi.c.2673) FastCGI-stderr: #3 /var/www/include/admin/upgrader.inc.php(328): call_user_func_array('serendipity_rem...', Array)
2016-01-04 15:56:34: (mod_fastcgi.c.2673) FastCGI-stderr: #4 /var/www/serendipity_admin.php(256): require('/var/www/includ...')
2016-01-04 15:56:34: (mod_fastcgi.c.2673) FastCGI-stderr: #5 {main}
2016-01-04 15:56:34: (mod_fastcgi.c.2673) FastCGI-stderr:   thrown in /var/www/include/functions_upgrader.inc.php on line 340
```

The problem is not that the file removal failed - if the rights are missing, that should be a server problem. The problem is that the upgrader should not fail with an internal server error showing a stacktrace, but detect the error and go back to the upgrader screen explaining what went wrong.

PS: See also how the stack track is still truncationg all the relevant file paths. Did we never arrive at fixing that?

**Comment by gnuheidix** [comment]
I've noticed this issue as well. last 2.1-beta to 2.1-rc1

The updater crashes when he tries to access something, he is not supposed to access. In this example: my .git directory, which shouldn't be accessible by the webserver at all. I have enabled the webserver access for a very short time so that the updater can do his job.

Furthermore, the updater should check, whether the SQLite-DB is writable. In my case, it wasn't so I had to run the updater twice. see #427 as well

```
[26-Jan-2017 18:14:16 Europe/Berlin] PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/srv/gnuheidix.de/.git): failed to open dir: Permission denied in /srv/gnuheidix.de/include/functions_upgrader.inc.php:340
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct('/srv/gnuheidix....', 0)
#1 /srv/gnuheidix.de/include/functions_upgrader.inc.php(340): RecursiveDirectoryIterator->getChildren()
#2 /srv/gnuheidix.de/include/admin/upgrader.inc.php(328): serendipity_removeDeadFiles_SPL('/srv/gnuheidix....', Array, Array, true)
#3 /srv/gnuheidix.de/serendipity_admin.php(253): require('/srv/gnuheidix....')
#4 {main}
  thrown in /srv/gnuheidix.de/include/functions_upgrader.inc.php on line 340
```

**Comment by garvinhicking** [comment]
Sorry it took us some time to address this. We have now fixed the Iterator to skip unreadable files. :-)

The sqlite writable check will be part of our #427 issue fix which we will address in the next version of Serendipity properly. Thanks a lot for your report!
