### ISSUE TITLE
Bug in Spamblock/Akismet?

### ISSUE THREAD

**Issue by ddeimeke** [s9y/Serendipity#411]
There seems to be an error with Akismet, maybe they changed their API.

```
== ERROR-REPORT (BETA/ALPHA-BUILDS) == 
Warning: preg_match() expects parameter 2 to be string, array given in /srv/www/deimeke.net/dirk/blog/bundled-libs/HTTP/Request2.php on line 284.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.


Fatal error: Uncaught exception 'ErrorException' with message 'Warning: preg_match() expects parameter 2 to be string, array given' in /srv/www/deimeke.net/dirk/blog/bundled-libs/HTTP/Request2.php:284 Stack trace: #0 [internal function]: errorToExceptionHandler(2, 'preg_match() ex...', '/srv/www/deimek...', 284, Array) #1 /srv/www/deimeke.net/dirk/blog/bundled-libs/HTTP/Request2.php(284): preg_match('![\\x00-\\x1f\\x7f...', Array) #2 /srv/www/deimeke.net/dirk/blog/bundled-libs/HTTP/Request2.php(215): HTTP_Request2->setMethod(Array) #3 /srv/www/deimeke.net/dirk/blog/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php(553): HTTP_Request2->__construct('http://xxx...', Array) #4 /srv/www/deimeke.net/dirk/blog/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php(659): serendipity_event_spamblock->akismetRequest('341b7642e882', Array, Array) #5 /srv/www/deimeke.net/dirk/blog/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php(1034): serendipity_event_spamblock->getBlacklist('a in /srv/www/deimeke.net/dirk/blog/bundled-libs/HTTP/Request2.php on line 284
```

**Comment by onli** [comment]
@ddeimeke Could you check whether https://github.com/s9y/Serendipity/commit/d973e999333b473ee37943f042e0b463c51584bd fixes this for you? Are you on a PHP version < 5.6?

**Comment by ddeimeke** [comment]
Unfortunately only the error message changes.

```
== ERROR-REPORT (BETA/ALPHA-BUILDS) ==
Warning: preg_match() expects parameter 2 to be string, array given in /srv/www/deimeke.net/dirk/blog/bundled-libs/HTTP/Request2.php on line 284.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.


 Fatal error: Uncaught exception 'ErrorException' with message 'Warning: preg_match() expects parameter 2 to be string, array given' in /srv/www/deimeke.net/dirk/blog/bundled-libs/HTTP/Request2.php:284 Stack trace: #0 [internal function]: errorToExceptionHandler(2, 'preg_match() ex...', '/srv/www/deimek...', 284, Array) #1 /srv/www/deimeke.net/dirk/blog/bundled-libs/HTTP/Request2.php(284): preg_match('![\\x00-\\x1f\\x7f...', Array) #2 /srv/www/deimeke.net/dirk/blog/bundled-libs/HTTP/Request2.php(215): HTTP_Request2->setMethod(Array) #3 /srv/www/deimeke.net/dirk/blog/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php(557): HTTP_Request2->__construct('http:// 341b764...', Array) #4 /srv/www/deimeke.net/dirk/blog/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php(663): serendipity_event_spamblock->akismetRequest(' 341b7642e882', Array, Array) #5 /srv/www/deimeke.net/dirk/blog/plugins/serendipity_event_spamblock/serendipity_event_spamblock.php(1038): serendipity_event_spamblock->getBlacklist(' in /srv/www/deimeke.net/dirk/blog/bundled-libs/HTTP/Request2.php on line 284
```

**Comment by ddeimeke** [comment]
Just forgot to mention:

Serendipity 2.1-beta1 und PHP 5.6.22

**Comment by onli** [comment]
Sorry, that was my mistake, I missed giving him the request method, for which he then used the options array. https://github.com/s9y/Serendipity/commit/f9482cc1aaac86f410ef79cd59343889362d2e6c should fix this.

**Comment by ddeimeke** [comment]
Test successful.

**Comment by onli** [comment]
Then I'll close here. Thanks for reporting the bug!
