### ISSUE TITLE
Exception in AdapterFileAbstract.php on saving article

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#597]
When I install the current git and save an article I get this error in the iframe that usually shows the status messages:

```
Warning: unlink(/home/hanno/websites/q2.re/htdocs//templates_c/ae): Is a directory in /home/hanno/websites/q2.re/htdocs/bundled-libs/voku/simple-cache/src/voku/cache/AdapterFileAbstract.php on line 171.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.



Fatal error:  Uncaught ErrorException: Warning: unlink(/home/hanno/websites/q2.re/htdocs//templates_c/ae): Is a directory in /home/hanno/websites/q2.re/htdocs/bundled-libs/voku/simple-cache/src/voku/cache/AdapterFileAbstract.php:171
Stack trace:
#0 [internal function]: errorToExceptionHandler(2, 'unlink(/home/ha...', '/home/hanno/web...', 171, Array)
#1 /home/hanno/websites/q2.re/htdocs/bundled-libs/voku/simple-cache/src/voku/cache/AdapterFileAbstract.php(171): unlink('/home/hanno/web...')
#2 /home/hanno/websites/q2.re/htdocs/bundled-libs/voku/simple-cache/src/voku/cache/Cache.php(430): voku\cache\AdapterFileAbstract->removeAll()
#3 /home/hanno/websites/q2.re/htdocs/include/functions.inc.php(1416): voku\cache\Cache->removeAll()
#4 /home/hanno/websites/q2.re/htdocs/include/functions_entries.inc.php(1479): serendipity_cleanCache()
#5 /home/hanno/websites/q2.re/htdocs/include/functions_config.inc.php(832): serendipity_updertEntry(Array)
#6 /home/hanno/websites/q2.re/htdocs/serendipity_admin.php(52): serendipity_iframe(Array,  in /home/hanno/websites/q2.re/htdocs/bundled-libs/voku/simple-cache/src/voku/cache/AdapterFileAbstract.php on line 171

**Comment by onli** [comment]
Oh, confirmed. We are using it wrong: templates_c should not be set as cache dir, but a directory in templates_c, because removeAll() will remove all files in the cache directory.

The nice thing: voku/simple-cache should automatically create the cache dir for us. Thus the fix would be simple:

Replace https://github.com/s9y/Serendipity/blob/f5d5b73c26ecbf73a530ea68ce062d977abf0c04/include/functions.inc.php#L1388

with

    $cacheDir = $serendipity['serendipityPath'] . '/templates_c/simple_cache';

Could you confirm that this patch works for you?


//cc @voku

**Comment by onli** [comment]
This should work now, so I will close here.
