### ISSUE TITLE
[serendipity_event_guestbook] Installation fail

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#718]
Installing serendipity_event_guestbook on current `master` w/ PHP 7.3 (bc of #686):

```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/plugins/serendipity_event_guestbook/serendipity_event_guestbook.php on line 1299.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.

Fatal error: Uncaught ErrorException: Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/plugins/serendipity_event_guestbook/serendipity_event_guestbook.php:1299
Stack trace:
#0 /var/www/html/include/plugin_api.inc.php(679): errorToExceptionHandler(2, '"continue" targ...', '/var/www/html/p...', 1299, Array)
#1 /var/www/html/include/plugin_api.inc.php(679): include()
#2 /var/www/html/include/plugin_api.inc.php(262): serendipity_plugin_api::load_plugin('serendipity_eve...', '0', 'serendipity_eve...')
#3 /var/www/html/include/admin/plugins.inc.php(412): serendipity_plugin_api::create_plugin_instance('serendipity_eve...', NULL, 'event', '0', 'serendipity_eve...')
#4 /var/www/html/serendipity_admin.php(133): include('/var/www/html/i...')
#5 {main}
thrown in /var/www/html/plugins/serendipity_event_guestbook/serendipity_event_guestbook.php on line 1299

== ERROR-REPORT (BETA/ALPHA-BUILDS) ==
Fatal Error: Uncaught ErrorException: Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/plugins/serendipity_event_guestbook/serendipity_event_guestbook.php:1299
Stack trace:
#0 /var/www/html/include/plugin_api.inc.php(679): errorToExceptionHandler(2, '"continue" targ...', '/var/www/html/p...', 1299, Array)
#1 /var/www/html/include/plugin_api.inc.php(679): include()
#2 /var/www/html/include/plugin_api.inc.php(262): serendipity_plugin_api::load_plugin('serendipity_eve...', '0', 'serendipity_eve...')
#3 /var/www/html/include/admin/plugins.inc.php(412): serendipity_plugin_api::create_plugin_instance('serendipity_eve...', NULL, 'event', '0', 'serendipity_eve...')
#4 /var/www/html/serendipity_admin.php(133): include('/var/www/html/i...')
#5 {main}
thrown in /var/www/html/plugins/serendipity_event_guestbook/serendipity_event_guestbook.php on line 1299.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.

Fatal error: Uncaught ErrorException: Fatal Error: Uncaught ErrorException: Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/plugins/serendipity_event_guestbook/serendipity_event_guestbook.php:1299
Stack trace:
#0 /var/www/html/include/plugin_api.inc.php(679): errorToExceptionHandler(2, '"continue" targ...', '/var/www/html/p...', 1299, Array)
#1 /var/www/html/include/plugin_api.inc.php(679): include()
#2 /var/www/html/include/plugin_api.inc.php(262): serendipity_plugin_api::load_plugin('serendipity_eve...', '0', 'serendipity_eve...')
#3 /var/www/html/include/admin/plugins.inc.php(412): serendipity_plugin_api::create_plugin_instance('serendipity_eve...', NULL, 'event', '0', 'serendipity_eve...')
#4 /var/www/html/serendipity_admin.php(133): include('/var/www/html/i...')
#5 {main}
thrown in /var/www/html/plugins/serendipity_event_guestbook/serendipity_event_guestbook.php:1299
Stack trace:
#0 /var/www/html/include/compat.inc.php(254): errorToExceptionHandler(1 in /var/www/html/plugins/serendipity_event_guestbook/serendipity_event_guestbook.php on line 1299
```

**Comment by onli** [comment]
This issue was linked in the jQuery upgrade issues. The very little jQuery code the plugin does indeed contain is fully compatible though.

For the error reported here, that's only a warning that the error handler back then elevated to an error. It (and more) will be fixed with https://github.com/s9y/additional_plugins/pull/190.

**Comment by onli** [comment]
The fix was merged.
