### ISSUE TITLE
[serendipity_event_osm] Installation fail

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#721]
Installing serendipity_event_osm on current master w/ PHP 7.3 (bc of #686) (This error is persistent, meaning I have to delete the plugin directory to even be able to get back into the backend.):

```
Warning: Use of undefined constant PLUGIN_PAGE_NUGGET_NOSHOW - assumed 'PLUGIN_PAGE_NUGGET_NOSHOW' (this will throw an Error in a future version of PHP) in /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php on line 86.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.

Fatal error: Uncaught ErrorException: Warning: Use of undefined constant PLUGIN_PAGE_NUGGET_NOSHOW - assumed 'PLUGIN_PAGE_NUGGET_NOSHOW' (this will throw an Error in a future version of PHP) in /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php:86
Stack trace:
#0 /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php(86): errorToExceptionHandler(2, 'Use of undefine...', '/var/www/html/p...', 86, Array)
#1 /var/www/html/include/plugin_api.inc.php(1623): serendipity_event_osm->introspect_config_item('title', Object(serendipity_property_bag))
#2 /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php(29): serendipity_plugin->get_config('title')
#3 /var/www/html/include/plugin_api.inc.php(1026): serendipity_event_osm->generate_content(NULL)
#4 /var/www/html/include/plugin_api.inc.php(1102): serendipity_plugin_api::get_plugin_title(Object(serendipity_event_osm))
#5 /var/www/html/include/plugin_api.inc.php(266): serendipity_plugin_api::get_event_plugins(false, true)
#6 /var/www/ht in /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php on line 86

== ERROR-REPORT (BETA/ALPHA-BUILDS) ==
Fatal Error: Uncaught ErrorException: Warning: Use of undefined constant PLUGIN_PAGE_NUGGET_NOSHOW - assumed 'PLUGIN_PAGE_NUGGET_NOSHOW' (this will throw an Error in a future version of PHP) in /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php:86
Stack trace:
#0 /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php(86): errorToExceptionHandler(2, 'Use of undefine...', '/var/www/html/p...', 86, Array)
#1 /var/www/html/include/plugin_api.inc.php(1623): serendipity_event_osm->introspect_config_item('title', Object(serendipity_property_bag))
#2 /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php(29): serendipity_plugin->get_config('title')
#3 /var/www/html/include/plugin_api.inc.php(1026): serendipity_event_osm->generate_content(NULL)
#4 /var/www/html/include/plugin_api.inc.php(1102): serendipity_plugin_api::get_plugin_title(Object(serendipity_event_osm))
#5 /var/www/html/include/plugin_api.inc.php(266): serendipity_plugin_api::get_event_plugins(false, true)
#6 /var/www/ht in /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php on line 86.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.

Fatal error: Uncaught ErrorException: Fatal Error: Uncaught ErrorException: Warning: Use of undefined constant PLUGIN_PAGE_NUGGET_NOSHOW - assumed 'PLUGIN_PAGE_NUGGET_NOSHOW' (this will throw an Error in a future version of PHP) in /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php:86
Stack trace:
#0 /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php(86): errorToExceptionHandler(2, 'Use of undefine...', '/var/www/html/p...', 86, Array)
#1 /var/www/html/include/plugin_api.inc.php(1623): serendipity_event_osm->introspect_config_item('title', Object(serendipity_property_bag))
#2 /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php(29): serendipity_plugin->get_config('title')
#3 /var/www/html/include/plugin_api.inc.php(1026): serendipity_event_osm->generate_content(NULL)
#4 /var/www/html/include/plugin_api.inc.php(1102): serendipity_plugin_api::get_plugin_title(Object(serendipity_event_osm))
#5 /var/www/html/include/plugin_api.inc.php(266): serendipity_plugin_api::get_eve in /var/www/html/plugins/serendipity_event_osm/serendipity_event_osm.php on line 86
```

**Comment by surrim** [comment]
Thanks for creating this issue. I fixed it in commit https://github.com/s9y/additional_plugins/commit/6dc512b1c87c88fdea6fdc499b3b73ac92b5a810. When the [pull request](https://github.com/s9y/additional_plugins/pull/118) is accepted, this issue can be closed.

**Comment by onli** [comment]
The mentioned PR is merged.
