### ISSUE TITLE
[serendipity_event_usergallery] Error message when clicking image

### ISSUE THREAD

**Issue by yellowled** [s9y/Serendipity#722]
Installed said plugin for testing #686 (current `master`, php7.3). Clicking an image in the gallery gives me:

```
Fatal error: Uncaught ErrorException: Notice: The each() function is deprecated. This message will be suppressed on further calls in /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php:1031 Stack trace: #0 [internal function]: errorToExceptionHandler(8192, 'The each() func...', '/var/www/html/p...', 1031, Array) #1 /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php(1031): each(Array) #2 /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php(451): serendipity_event_usergallery->displayImage('1', 'i.name', 'ASC') #3 /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php(734): serendipity_event_usergallery->show() #4 /var/www/html/include/plugin_api.inc.php(1190): serendipity_event_usergallery->event_hook('entries_header', Object(serendipity_property_bag), Array, '') #5 /var/www/html/include/functions_smarty.inc.php(565): serendipity_plugin_api::hook_event('entries_header', Array, '') #6 /var/www in /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php on line 1031
== ERROR-REPORT (BETA/ALPHA-BUILDS) ==
Fatal Error: Uncaught ErrorException: Notice: The each() function is deprecated. This message will be suppressed on further calls in /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php:1031 Stack trace: #0 [internal function]: errorToExceptionHandler(8192, 'The each() func...', '/var/www/html/p...', 1031, Array) #1 /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php(1031): each(Array) #2 /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php(451): serendipity_event_usergallery->displayImage('1', 'i.name', 'ASC') #3 /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php(734): serendipity_event_usergallery->show() #4 /var/www/html/include/plugin_api.inc.php(1190): serendipity_event_usergallery->event_hook('entries_header', Object(serendipity_property_bag), Array, '') #5 /var/www/html/include/functions_smarty.inc.php(565): serendipity_plugin_api::hook_event('entries_header', Array, '') #6 /var/www in /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php on line 1031.
For more details set $serendipity['production'] = 'debug' in serendipity_config_local.inc.php to receive a stack-trace.

Fatal error: Uncaught ErrorException: Fatal Error: Uncaught ErrorException: Notice: The each() function is deprecated. This message will be suppressed on further calls in /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php:1031
Stack trace:
#0 [internal function]: errorToExceptionHandler(8192, 'The each() func...', '/var/www/html/p...', 1031, Array)
#1 /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php(1031): each(Array)
#2 /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php(451): serendipity_event_usergallery->displayImage('1', 'i.name', 'ASC')
#3 /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php(734): serendipity_event_usergallery->show()
#4 /var/www/html/include/plugin_api.inc.php(1190): serendipity_event_usergallery->event_hook('entries_header', Object(serendipity_property_bag), Array, '')
#5 /var/www/html/include/functions_smarty.inc.php(565): serendipity_plugin_api::hook_event('e in /var/www/html/plugins/serendipity_event_usergallery/serendipity_event_usergallery.php on line 1031
```

**Comment by onli** [comment]
This error is fixed by now, https://github.com/s9y/additional_plugins/commit/38f738fdf3736eb5e5c60e6bc808a74c5159b15d exchanged the `while list each` with a compatible  `foreach`. https://github.com/s9y/additional_plugins/pull/189 will provide additional compatibility with PHP 8 when merged, but that's only relevant for the exif option.

This issue was linked to the jquery compatibility story which is continuing with https://github.com/s9y/Serendipity/pull/873, but the usergallery plugin has no jQuery or javascript dependency. It just sets html params for the lightbox plugin and mentions jQuery there, which is probably why it was picked up in the search.
