### ISSUE TITLE
Output complete stacktrace

### ISSUE THREAD

**Issue by onli** [s9y/Serendipity#735]
Right now, we have a setup to control how PHP reacts to errors and exceptions. It is defined in https://github.com/s9y/Serendipity/blob/dafaae8db0795bcba2968a5e93a2d773b18a2f42/include/compat.inc.php#L122 I think that the stacktrace part of that is broken. Right now for example I get this message in my log:

```
[10-Jun-2020 15:58:10] WARNING: [pool www] child 11420 said into stderr: "Stack trace:"
[10-Jun-2020 15:58:10] WARNING: [pool www] child 11420 said into stderr: "#0 /var/www/virtual/onli2/html/s9y_dev/include/compat.inc.php(254): errorToExceptionHandler(1, 'Uncaught ErrorE...', '/var/www/virtua...', 38)"
[10-Jun-2020 15:58:10] WARNING: [pool www] child 11420 said into stderr: "#1 [internal function]: fatalErrorShutdownHandler()"
[10-Jun-2020 15:58:10] WARNING: [pool www] child 11420 said into stderr: "#2 {main}"
[10-Jun-2020 15:58:10] WARNING: [pool www] child 11420 said into stderr: "  thrown in /var/www/virtual/onli2/html/s9y_dev/include/admin/images.inc.php on line 38"

```

Note how the #0 args get shortened.

In the browser, I get this error:

```
Fatal error:  Uncaught ErrorException: Warning: Use of undefined constant NO_FILE_SELECTED - assumed 'NO_FILE_SELECTED' (this will throw an Error in a future version of PHP) in /var/www/virtual/onli2/html/s9y_dev/include/admin/images.inc.php:38
Stack trace:
#0 /var/www/virtual/onli2/html/s9y_dev/include/admin/images.inc.php(38): errorToExceptionHandler(2, 'Use of undefine...', '/var/www/virtua...', 38, Array)
#1 /var/www/virtual/onli2/html/s9y_dev/serendipity_admin.php(115): include('/var/www/virtua...')
#2 {main}
  thrown in /var/www/virtual/onli2/html/s9y_dev/include/admin/images.inc.php on line 38
```

Note how #0 and #1 gets shorted, while at least here the real error message is helpful enough.

Somehow related discussion was in https://github.com/s9y/Serendipity/issues/399#issuecomment-217852882 and the linked commit.

**Comment by onli** [comment]
Solved with https://github.com/s9y/Serendipity/commit/a42183c9982e461f4bcbcbdad662a6269259a352 🥳
