### ISSUE TITLE
database error when p is set to invalid value

### ISSUE THREAD

**Issue by hannob** [s9y/Serendipity#814]
I observed database errors in my php logs:
```
PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND isdraft = 'false'  AND timestamp <= 1695999000' at line 1 in [path]include/db/mysqli.inc.php:68
Stack trace:
#0 [path]include/db/mysqli.inc.php(68): mysqli_query()
#1 [path]include/functions_routing.inc.php(382): serendipity_db_query()
#2 [path]index.php(75): serveEntry()
#3 {main}
  thrown in [path]include/db/mysqli.inc.php on line 68
```

These appear due to attacking attempts on my blog that set an invalid p parameter. A minimal reproducer is calling the url https://[hostname]/?p= (i.e. empty 0 value)

I think the relevant code is here https://github.com/s9y/Serendipity/blob/master/include/functions_routing.inc.php#L374
```
    $id = (int)$matches[1];
    if ($id === 0) {
        $id = false;
    }

    $serendipity['GET']['action'] = 'read';
    $serendipity['GET']['id']     = $id;

    $title = serendipity_db_query("SELECT title FROM {$serendipity['dbPrefix']}entries WHERE id=$id AND isdraft = 'false' " . (!serendipity_db_bool($serendipity['showFutureEntries']) ? " AND timestamp <= " . serendipity_db_time() : ''), true);
```

It constructs a db query which will have "WHERE id=" (i.e. empty), which is not valid. It appears to me that the "$id = false;" is wrong here, it should ultimately at this point just throw an error and consider the request invald. We could just remove that "$id === 0" check. In case $id is 0 it will cause a 404 page a few lines below.

Please note: I observed this on multiple instances after updating to 2.5 beta1 and php 8.2. I haven't tested if it also happens with 2.4, but the code there is old, so I assume this is just a coincidence.

**Comment by onli** [comment]
Thanks @hannob ! I documented the fix in  https://github.com/s9y/Serendipity/commit/2ef0afd7bb85d2c00ebb1c5b64f32caeef68b637.
