### ISSUE TITLE
Install of 2.5 leads to type error, MySQLi, Hoster: Limacity

### ISSUE THREAD

**Issue by Flip1** [s9y/Serendipity#822]
I've tried installing 2.5 on an empty webspace.
The installation (easy option) was aborted with the following error:

Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, null given
include/db/mysqli.inc.php Zeile 66

Backtrace
#0 include/db/mysqli.inc.php(66): mysqli_query(NULL, 'SELECT * FROM s...')
#1 include/admin/installer.inc.php(325): serendipity_db_query('SELECT * FROM s...', false, 'both', false, false, false, true)
#2 serendipity_admin.php(260): require('/home/webpages/...')
#3 {main}

Hoster: Limacity
Version of MySQL or MariaDB is: 8.0.34-26

**Comment by garvinhicking** [comment]
Sadly we have no proper error reporting in place at this point where a database connection fails.

What happens is that probably your database credentials or hostname are wrong; PHP cannot connect to the server with the data you entered. Can you verify you use the right database name and port?

@onli - we should address a proper error reporting here, our serendipity_db_connect() doesn't do any of that :-O

**Comment by Flip1** [comment]
Yes, I'm sorry, it was my mistake. The installation was now successful.
But yes, this error message is really meaningless and could be improved.
